version: "3.7"

services:
  mongo1:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
  mongo2:
    image: "mongo:4.4"
    ports:
      - "27018:27017"
  mongo3:
    image: "mongo:4.4"
    ports:
      - "27019:27017"
